#!/bin/bash
bzippedfile=../zipped_data/enwiki-20170820-pages-articles-multistream.xml.bz2
dir_to_save=.
start=0
end=0
let n_blocks=0
let count_lines=0

outfile=$dir_to_save/beginning.xml
# since we only the for the final splitting we need not use the count_bytes for the iflag.
dd if=$bzippedfile of=$outfile.bz2 count=616 iflag=count_bytes status='none'
bzip2recover $outfile.bz2 2>/dev/null
lbzip2 -dc $dir_to_save/beginning.xml.bz2 > $outfile
trash-put $dir_to_save/*.bz2

